apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: service-b
  namespace: deleteme-1
  app: <%=app%>
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deployment-config.name: service-b
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-config.name: service-b
    spec:
      containers:
      - image: docker-registry.default.svc:5000/deleteme-1/service-b
        imagePullPolicy: Always
        name: default-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-01-28T09:09:12Z
    lastUpdateTime: 2020-01-28T09:09:12Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2020-01-28T09:39:14Z
    lastUpdateTime: 2020-01-28T09:39:19Z
    message: replication controller "service-b-3" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: Manual
    message: manual change
  latestVersion: 3
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
